version: '3.5'
services:
  service-auth:
    image: jinhong0719/dms-sms-service-auth:${VERSION}.RELEASE
    container_name: service-auth
    networks:
      - dms-sms-local
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
      - SMS_AWS_ID=${SMS_AWS_ID}
      - SMS_AWS_KEY=${SMS_AWS_KEY}
      - SMS_AWS_REGION=${SMS_AWS_REGION}
      - SMS_AWS_BUCKET=${SMS_AWS_BUCKET}
      - CHANGE_CONSUL_SQS_AUTH=${CHANGE_CONSUL_SQS_AUTH}
      - ALIGO_API_KEY=${ALIGO_API_KEY}
      - ALIGO_ACCOUNT_ID=${ALIGO_ACCOUNT_ID}
      - ALIGO_SENDER=${ALIGO_SENDER}
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=service-auth]

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: overlay
