name: upload_image

on:
  push:
    branches:
      - master

jobs:
  BUILD_AND_UPLOAD_IMAGE:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.4'
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Init submodule after clone
        run: git submodule update --init
      - name: Build golang to binary file
        run: make build
      - name: Build docker image
        run: VERSION=${{ secrets.VERSION }} make image
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to docker hub
        run: VERSION=${{ secrets.VERSION }} make upload
